// Messages qui défilent en bas de l'écran d'annonce d'une manche.
// À modifier librement : un message par ligne ; {code} est remplacé par le code de la partie.
export const TIPS = [
  "COMMENT REJOINDRE : SCANNE LE QR CODE, OU ENTRE {code} SUR TON TÉLÉPHONE",
  "RÈGLE N°1 : C'EST TOUJOURS LA FAUTE DU PRÉSENTATEUR",
  "RÈGLE N°2 : SI TU PERDS, NE PAS SE FIER À LA RÈGLE N°1",
  "INUTILE DE SOUDOYER LE PRÉSENTATEUR, IL EST BLINDÉ",
  "RÈGLE N°3 : LE PRÉSENTATEUR A TOUJOURS RAISON, MÊME QUAND IL A TORT",
  "ARTISTE : LE NOM DE FAMILLE SUFFIT",
  "GARDE TON ÉCRAN ALLUMÉ, ON S'OCCUPE DU RESTE",
  "TU CONNAIS LA CHANSON MAIS PAS LE TITRE ? C'EST LE DRAME DE TOUS LES BLIND TESTS",
  "UN BLIND TEST SANS MAUVAISE FOI N'EST PAS UN BLIND TEST",
  "CHANTER PLUS FORT NE DONNE AUCUN POINT… MAIS ON PEUT ESSAYER",
  "RETARDATAIRE ? SCANNE LE QR CODE EN BAS DE L'ÉCRAN ET REJOINS LA PARTIE EN COURS",
  "ÉCOUTE BIEN : LE PRÉSENTATEUR NE RÉPÈTE JAMAIS (SAUF QUAND IL A OUBLIÉ)",
];

export const tipsText = (code) => TIPS.map(t => t.replace('{code}', code || 'LE CODE AFFICHÉ')).join('   ✦   ');
